---
    name: Guard Main Branch
    on:
      pull_request:
        types:
          - auto_merge_enabled
        branches:
          - main
      merge_group:
    permissions:
      contents: read
    jobs:
      branch-check:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - name: Preamble
        run: |
          echo "ğŸ‰ A $EVENT triggered a ${{ runner.os }} job."
          echo "ğŸ” The branch is $BRANCH in $REPO."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Guard the main branch
        if: ${{ env.HEAD != 'staging' && env.HEAD != ''}}
        run: |
          echo "ğŸš« The main branch is protected."
          echo "ğŸš« Pull requests to main must come from staging branch."
          exit 1
      - name: Notify
        run: |
          echo "ğŸ“£ The job has been completed."
          echo "ğŸ”” The main branch is protected."
          echo "ğŸ This job's status is ${{ job.status }}."

